In [8]:
##librerias
import numpy as np


In [9]:
def jacobi(A, b, x0, epsilon, max_iter):
    n = len(b)
    x = x0.copy()
    for _ in range(max_iter):
        x_new = np.zeros_like(x)
        for i in range(n):
            x_new[i] = (b[i] - np.dot(A[i, :i], x[:i]) - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
        if np.linalg.norm(x_new - x) < epsilon:
            break
        x = x_new
    return x

In [10]:
def gauss_seidel(A, b, x0, epsilon, max_iter):
    n = len(b)
    x = x0.copy()
    for _ in range(max_iter):
        for i in range(n):
            x[i] = (b[i] - np.dot(A[i, :i], x[:i]) - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
        if np.linalg.norm(A @ x - b) < epsilon:
            break
    return x

In [11]:
def jor(A, b, x0, epsilon, max_iter, omega):
    n = len(b)
    x = x0.copy()
    for _ in range(max_iter):
        x_new = np.zeros_like(x)
        for i in range(n):
            x_new[i] = (1 - omega) * x[i] + (omega / A[i, i]) * (b[i] - np.dot(A[i, :i], x_new[:i]) - np.dot(A[i, i+1:], x[i+1:]))
        if np.linalg.norm(x_new - x) < epsilon:
            break
        x = x_new
    return x

In [12]:
def sor(A, b, x0, epsilon, max_iter, omega):
    n = len(b)
    x = x0.copy()
    for _ in range(max_iter):
        for i in range(n):
            x[i] = (1 - omega) * x[i] + (omega / A[i, i]) * (b[i] - np.dot(A[i, :i], x[:i]) - np.dot(A[i, i+1:], x[i+1:]))
        if np.linalg.norm(A @ x - b) < epsilon:
            break
    return x

In [36]:
# Sistema tridiagonal
n = 10000
diagonal = np.ones(n) * 4
off_diagonal = np.ones(n - 1) * -1
A = np.diag(diagonal) + np.diag(off_diagonal, -1) + np.diag(off_diagonal, 1)
b = np.ones(n) * 2
x_exact = np.ones(n)

In [37]:
x0 = np.zeros(n)
epsilon = 1e-6
max_iter = 10000
omega_jor = 1.5
omega_sor = 1.25

In [38]:
x_jacobi = jacobi(A, b, x0, epsilon, max_iter)
x_gauss_seidel = gauss_seidel(A, b, x0, epsilon, max_iter)
x_jor = jor(A, b, x0, epsilon, max_iter, omega_jor)
x_sor = sor(A, b, x0, epsilon, max_iter, omega_sor)

In [39]:
print(f"Metodo Jacobi:\n{x_jacobi}")

Metodo Jacobi:
[0.73205081 0.92820323 0.98076211 ... 0.98076211 0.92820323 0.73205081]


In [40]:
print(f"Metodo Gauss-Seidel:\n{x_gauss_seidel}")


Metodo Gauss-Seidel:
[0.73205081 0.92820323 0.98076211 ... 0.98076211 0.92820323 0.73205081]


In [41]:
print(f"Metodo OR:\n{x_jor}")

Metodo OR:
[0.73205081 0.92820323 0.98076211 ... 0.98076211 0.92820323 0.73205081]


In [42]:
print(f"Metodo SOR:\n{x_sor}")

Metodo SOR:
[0.73205081 0.92820323 0.98076211 ... 0.98076211 0.92820323 0.73205081]


In [43]:
error_jacobi = np.linalg.norm(x_jacobi - x_exact)
error_gauss_seidel = np.linalg.norm(x_gauss_seidel - x_exact)
error_jor = np.linalg.norm(x_jor - x_exact)
error_sor = np.linalg.norm(x_sor - x_exact)

In [44]:
print(f"Error Jacobi: {error_jacobi}")
print(f"Error Gauss-Seidel: {error_gauss_seidel}")
print(f"Error JOR: {error_jor}")
print(f"Error SOR: {error_sor}")

Error Jacobi: 0.3933198988221523
Error Gauss-Seidel: 0.39331989494951225
Error JOR: 0.3933198931927035
Error SOR: 0.3933198931908167
